name: Take A Hike CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install root dependencies
        run: yarn
      - name: Install server dependencies
        run: cd server && yarn
      - name: Install client dependencies
        run: cd client && yarn
      - name: Lint
        run: yarn lint
  build:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn
      - name: Build
        run: yarn build
  server-tests:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: Install root dependencies
        run: yarn
      - name: Install server dependencies
        run: cd server && yarn
      - name: Server unit tests
        run: yarn test:server
  client-tests:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: Install root dependencies
        run: yarn
      - name: Install client dependencies
        run: cd client && yarn
      - name: Client unit tests
        run: yarn test:client
  deploy:
    runs-on: ubuntu-latest
    needs: [build, server-tests, client-tests]
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL_ADDRESS}}
